site_name: 摄影摄像入门教程
nav:
    - 序言与介绍:
        - 快速开始: index.md
        - 关于本项目: about.md
    - 前置知识篇:
        - “像”: image.md
    - 成像篇:
        - 认识镜头: lens.md
        - 了解对焦: focus.md
        - "*滤镜": A_filter.md
    - 记录篇:
        - 了解 ISO: iso.md
        - 认识数码相机: camera.md
        - 认识胶片: film.md
        - 了解曝光: exposure.md
    - 图像处理篇:
        - 了解色彩: color-science.md
        - 视频编码: encoding.md
        - 图像压缩与 RAW: raw.md
    - 杂项:
        - 了解声音: sound.md
        - 影像稳定: stabilization.md

theme: material
repo_url: https://github.com/troyxun/photography-tutorial
repo_name: troyxun/photography-tutorial
site_description:
site_author: Sam Tong, Troy Xun
copyright: Copyright © 2024 - 2025 Sam Tong & Troy Xun

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
          tex_inline_wrap: ["$", "$"]
          tex_block_wrap: ["$$", "$$"]
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js

extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
plugins:
    - glightbox