site_name: 摄影摄像入门教程
nav:
    - 序言与介绍:
        - 快速开始: index.md
        - 关于本项目: about.md
    - 前置知识篇:
        - 了解光学: optics.md
    - 成像篇:
        - 认识镜头: lens.md
        - 了解对焦: focus.md
    - 记录篇:
        - 认识相机: camera.md
        - 了解曝光: exposure.md
        - 了解 ISO: iso.md
    - 图像处理篇:
        - 了解色彩: color-science.md
        - 视频编码: encoding.md
        - 图像压缩与 RAW: raw.md
    - 杂项:
        - 了解声音: sound.md
        - 影像稳定: stabilization.md

theme: material
repo_url: https://github.com/troyxun/photography-tutorial
repo_name: TSStudio/photography-tutorial
site_description:
site_author: Sam Tong, Troy Xun
copyright: Copyright © 2024 - 2025 Sam Tong & Troy Xun with ❤️

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - attr_list
    - md_in_html

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
    - glightbox